name: Karma
version: 0.1
description: Karmic auto-ranking
author: tommytony
website: https://github.com/taoneill/karma

main: bukkit.tommytony.karma.Karma

commands:
  karma:
    description: The main karma command
    usage: Karma> Use /karma to check your karma points. Use /karma <person> to see points of others. Use /karma gift <person> <amount> to give karma to another player. Use /karma ranks to enumerate ranks. Use /karma builder <person> to give another player build rights. Use /k as an alias.
    aliases: k
    permission: